version: '3'
services:
   db:
     image: mariadb
     ports:
       - "3306:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${mySqlRootPassword}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: ${mySqlUser}
       MYSQL_PASSWORD: ${mySqlPassword}
   pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${mySqlRootPassword}
    ports:
      - 8080:${internalPort}
    links:
      - db:db
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "${externalPort}:${internalPort}"
       - "443:443"
     restart: always
     volumes:
       - .:/var/www/html/
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${mySqlUser}
       WORDPRESS_DB_PASSWORD: ${mySqlPassword}
volumes:
  db_data:

